export default [
    {   id: 1,
        marca: "armani",
        modelo: "my way",
        img: "myWay.png",
        ml: "60 ml",
    },{  id: 2,
        marca: "armani",
        modelo: "si",
        img: "si.png",
        ml: "60 ml",
    },{  id: 3,
        marca: "armani",
        modelo: "code",
        img: "codeM.png",
        ml: "60 ml",
    },{  id: 4,
        marca: "armani",
        modelo: "stronger with you",
        img: "you.png",
        ml: "60 ml",
    },{  id: 5,
        marca: "armani",
        modelo: "code",
        img: "codeH.png",
        ml: "60 ml",
    },{  id: 6,
        marca: "armani",
        modelo: "acqua di gio",
        img: "acquaDiGioH.png",
        ml: "60 ml",
    }
]