export default [
    {
        id: 1,
        marca: "paco rabanne",
        modelo: "black xs",
        img: "blackXsH.png",
        ml: "60 ml",
    },
    {
        id: 2,
        marca: "paco rabanne",
        modelo: "black xs",
        img: "blackXsM.png",
        ml: "60 ml",
    },
    {
        id: 3,
        marca: "paco rabanne",
        modelo: "black xs lexcess",
        img: "blackXsLexcessH.png",
        ml: "60 ml",
    },
    {
        id: 4,
        marca: "paco rabanne",
        modelo: "black xs lexcess",
        img: "blackXsLexcessM.png",
        ml: "60 ml",
    },
    {
        id: 5,
        marca: "paco rabanne",
        modelo: "olympea",
        img: "olympea.png",
        ml: "60 ml",
    },
    {
        id: 6,
        marca: "paco rabanne",
        modelo: "invictus",
        img: "invictus.png",
        ml: "60 ml",
    },
    {
        id: 7,
        marca: "paco rabanne",
        modelo: "lady million",
        img: "ladyMillion.png",
        ml: "60 ml",
    },
    {
        id: 8,
        marca: "paco rabanne",
        modelo: "one million",
        img: "oneMillion.png",
        ml: "60 ml",
    },
    {
        id: 9,
        marca: "paco rabanne",
        modelo: "pure xs",
        img: "pureXsM.png",
        ml: "60 ml",
    },
    {
        id: 10,
        marca: "paco rabanne",
        modelo: "pure xs",
        img: "pureXsH.png",
        ml: "60 ml",
    },
    {
        id: 11,
        marca: "paco rabanne",
        modelo: "phantom",
        img: "phantom.png",
        ml: "60 ml",
    }
]